runtime: go
api_version: go1
vm: true

handlers:

- url: /static
  static_dir: static
#- url: /favicon.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico

- url: /.*
  script: _go_main
